### ISSUE TITLE
Request (NOT AN ISSUE)

### ISSUE THREAD

**Issue by 948347893875338** [dharmik2319/geotastic-helper#1]
heeeeeeeeeey
can i upload this to greasyfork?
asking for permission since i dont want something to happen

**Comment by 948347893875338** [comment]
Adding on to this (if you dont mind),
do you want a license on it?
![image](https://github.com/dharmik2319/geotastic-helper/assets/121643321/ebb2a7f6-b700-4ad9-a3fa-78c3a21dda91)

**Comment by dharmik2319** [comment]
GPL v3 would be nice

**Comment by dharmik2319** [comment]
i have added a license to this repo as well, which i had somehow forgotten earlier

**Comment by 948347893875338** [comment]
Just gonna suggest an edit to put into the main code here (since i put in greasyfork auto-syncing)
// @license GNU GPLv3
just so it auto-syncs and the license and so its actually inside the code 
(im pretty sure its the correct way to put it in)

**Comment by dharmik2319** [comment]
oh yes, thanks.
please do share the link to the greasyfork page as well.
