### ISSUE TITLE
How to use the other modes?

### ISSUE THREAD

**Issue by LukeLukee3** [dharmik2319/geotastic-helper#8]
I want to use the mode that opens google maps on another tab how do I do that?

**Comment by dharmik2319** [comment]
Well, it is supposed to be done by [pressing 2](https://github.com/dharmik2319/geotastic-helper/blob/master/README.md#2---open-the-target-coordinates-in-google-maps-in-another-tab-to-cross-reference-with-the-guess-map) but in the current status it may or may not work as intended (just like the other features). Also, are you able to see the Coordinates with 1 or is the marker placed for you?

**Comment by dharmik2319** [comment]
closing because issue is stale
